- name: Start Minecraft
  hosts: Chicago
  tasks:
    - name: Start Minecraft Docker container
      community.docker.docker_container:
        name: akunacraft
        image: itzg/minecraft-server:latest
        pull: true
        labels:
          autoheal: 'true'
          diun.enable: 'true'
          diun.watch_repo: 'true'
          diun.notify_on: new;update
          diun.sort_tags: semver
          diun.max_tags: '1'
          diun.include_tags: '^latest$'
        restart_policy: unless-stopped
        env:
          VERSION: 1.21.8
          WHITELIST: SegFault86,mahdiqazwini,paperboat13,eric6356
          OPS: SegFault86
          DIFFICULTY: normal
          HARDCORE: 'false'
          SPAWN_PROTECTION: '0'
          VIEW_DISTANCE: '32'
          EULA: 'true'
          MEMORY: 4G
          ENABLE_RCON: 'false'
          MOTD: The New Wave in Mining and Crafting
          ICON: 'https://media.licdn.com/dms/image/v2/C4E0BAQGaxHYyl3mOAg/company-logo_200_200/company-logo_200_200/0/1631345113926?e=2147483647&v=beta&t=aEHK7jDfaltFiwidIK-g6vlaibeCQvpk7pbtQtcjVL0'
          OVERRIDE_ICON: 'true'
        volumes:
          - minecraft-2025:/data
        published_ports:
          - 25565:25565
        keep_volumes: false
        state: started
