- name: Stop Minecraft
  ansible.builtin.import_playbook: stop.yaml

- name: Uninstall Minecraft
  hosts: Montreal
  tasks:
    - name: Remove Minecraft data Docker volume
      community.docker.docker_volume:
        volume_name: minecraft-forever
        state: absent
    - name: Remove Minecraft data Docker volume directory
      become: true
      ansible.builtin.file:
        path: /data/minecraft-forever
        state: absent

    - name: Read homelab config
      ansible.builtin.slurp:
        src: '{{ansible_facts["user_dir"]}}/.homelab.json'
      register: homelab_config_file
    - name: Set homelab_config variable
      ansible.builtin.set_fact:
        homelab_config: '{{homelab_config_file.content|b64decode|from_json}}'

    - name: Delete from Postgres table service_data
      community.postgresql.postgresql_query:
        login_host: '{{homelab_config.database.host}}'
        login_user: '{{homelab_config.database.user}}'
        login_password: '{{homelab_config.database.password}}'
        login_db: '{{homelab_config.database.name}}'
        query: 'DELETE FROM service_data WHERE service = %s;'
        positional_args:
          - minecraft_forever
    - name: Delete from Postgres table service_port
      community.postgresql.postgresql_query:
        login_host: '{{homelab_config.database.host}}'
        login_user: '{{homelab_config.database.user}}'
        login_password: '{{homelab_config.database.password}}'
        login_db: '{{homelab_config.database.name}}'
        query: 'DELETE FROM service_port WHERE service = %s;'
        positional_args:
          - minecraft_forever
    - name: Delete from Postgres table service
      community.postgresql.postgresql_query:
        login_host: '{{homelab_config.database.host}}'
        login_user: '{{homelab_config.database.user}}'
        login_password: '{{homelab_config.database.password}}'
        login_db: '{{homelab_config.database.name}}'
        query: 'DELETE FROM service WHERE name = %s;'
        positional_args:
          - minecraft_forever
